# Generated by Django 3.2.13 on 2022-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('aciklama', models.TextField()),
                ('tamamlandi', models.BooleanField(default=False)),
            ],
        ),
    ]
